/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MedicinesIndexRouteImport } from './routes/medicines/index'
import { Route as MedicinesNewRouteImport } from './routes/medicines/new'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicinesIndexRoute = MedicinesIndexRouteImport.update({
  id: '/medicines/',
  path: '/medicines/',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicinesNewRoute = MedicinesNewRouteImport.update({
  id: '/medicines/new',
  path: '/medicines/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/medicines/new': typeof MedicinesNewRoute
  '/medicines': typeof MedicinesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/medicines/new': typeof MedicinesNewRoute
  '/medicines': typeof MedicinesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/medicines/new': typeof MedicinesNewRoute
  '/medicines/': typeof MedicinesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/register' | '/medicines/new' | '/medicines'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/register' | '/medicines/new' | '/medicines'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/medicines/new'
    | '/medicines/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  MedicinesNewRoute: typeof MedicinesNewRoute
  MedicinesIndexRoute: typeof MedicinesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medicines/': {
      id: '/medicines/'
      path: '/medicines'
      fullPath: '/medicines'
      preLoaderRoute: typeof MedicinesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medicines/new': {
      id: '/medicines/new'
      path: '/medicines/new'
      fullPath: '/medicines/new'
      preLoaderRoute: typeof MedicinesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  MedicinesNewRoute: MedicinesNewRoute,
  MedicinesIndexRoute: MedicinesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
